### ISSUE TITLE
Use with Flowable

### ISSUE THREAD

**Issue by rossdanderson** [opentracing-contrib/java-rxjava#11]
Hi, is there any reason that this does not cover FlowableSubscriber for Flowable use cases, or has this simply not been implemented so far?

**Comment by malafeev** [comment]
@rossdanderson it was not implemented. PR is welcome.

**Comment by rossdanderson** [comment]
Thanks, I'll try to take a look over the coming month

**Comment by malafeev** [comment]
fixed via #12
